### PR TITLE
1: Added entry point for all scripts

### PR DESCRIPTION
**Pull request by edvein-rin**
It works, but...
I didn't add command for "scrape_url_and_check_broken_links" because you should separate them. The same with "scrape_email_and_socmedia". It really would be better if modules were like these: "scrape email", "scrape socmedia". All funcs should do only one thing, the same with scripts. Just add a chain querries like: "scrape url" + "scrape socmedia" + "check broken links". And don't add "NO new links". Add "WITH new links". It's logical, and easier to add in the chain: "scrape url" + "new links".
Sorry, for not writing all commands, but it won't be needable if you use separated modules. Good luck!
[Issue #1](https://github.com/johncoleman83/domain_scraper/issues/1)

### CODE REVIEW

**Comment by johncoleman83** [comment]
Thanks sorry to delay, looks good.  I will review this soon and likely merge.  I may have a few suggestions, but will probably just merge and fix myself.  Looks really good though, just got to go now but will review soon.

**Comment by johncoleman83** [comment]
Thanks for your contribution!  Even though this is a total WIP and probably should not yet be merged, I see what you are going for and will quickly revise the things lacking in these updates.

**Comment by edvein-rin** [comment]
Thank you for your feedback, and sorry for any troubles. I glad to help Open Source.

**Comment by johncoleman83** [comment]
You're welcome.  Also, thanks for your support.  Feel free to add yourself as a contributor.

**Pull request merged**
